name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: '1.5.1'
      - name: Install packages
        run: poetry install
      - name: Run isort
        run: poetry run isort --check --profile black .
      - name: Run mypy
        run: poetry run mypy --strict .
      - name: Run ruff
        run: poetry run ruff check .
      - name: Run pylint
        run: poetry run pylint --recursive=y .
      - name: Run flake8
        run: poetry run flake8 .
      - name: Run black check
        run: poetry run black --check .
