name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: '1.5.1'
      - name: Install packages
        run: poetry install
      - name: Run tests
        run: poetry run pytest .
